name: CI Pipeline

on:
  push:
    branches:
      - main
      - feature/ci-action
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Step 3: Build and run backend tests using Docker Compose
      - name: Build and run backend tests
        run: |
          docker-compose build backend backend_tests
          docker-compose run backend_tests